# Generated by Django 5.1.6 on 2025-04-29 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('kolicina', models.IntegerField()),
                ('stanje', models.CharField(max_length=100)),
                ('kategorija', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('protivnik', models.CharField(max_length=100)),
                ('lokacija', models.CharField(max_length=100)),
                ('rezultat', models.CharField(max_length=20)),
                ('opis', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
                ('prezime', models.CharField(max_length=100)),
                ('datum_rodenja', models.DateField()),
                ('pozicija', models.CharField(choices=[('GK', 'Golman'), ('DF', 'Branič'), ('MF', 'Vezni'), ('FW', 'Napadač')], max_length=2)),
                ('broj_dresa', models.IntegerField()),
                ('kategorija', models.CharField(choices=[('seniori', 'Seniori'), ('juniori', 'Juniori'), ('kadeti', 'Kadeti'), ('pioniri', 'Pioniri')], max_length=20)),
                ('golovi', models.IntegerField(default=0)),
                ('asistencije', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
                ('funkcija', models.CharField(max_length=100)),
                ('kontakt', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('zapisnik', models.TextField()),
                ('prisutni', models.ManyToManyField(to='main.staffmember')),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('golovi', models.IntegerField(default=0)),
                ('asistencije', models.IntegerField(default=0)),
                ('minute', models.IntegerField(default=0)),
                ('zuti_kartoni', models.IntegerField(default=0)),
                ('crveni_kartoni', models.IntegerField(default=0)),
                ('igrac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.player')),
                ('utakmica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.match')),
            ],
        ),
    ]
