# Generated by Django 5.1.6 on 2025-08-20 14:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('BALL', 'Lopta'), ('KIT', 'Dres')], max_length=4)),
                ('quantity', models.PositiveIntegerField()),
                ('condition', models.CharField(default='Ispravno', max_length=50)),
                ('purchase_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('home_or_away', models.CharField(choices=[('H', 'Suhača'), ('A', 'Gostovanje')], max_length=1)),
                ('opponent', models.CharField(max_length=100)),
                ('home_score', models.PositiveIntegerField(default=0)),
                ('away_score', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('U9', 'U9'), ('U11', 'U11'), ('MP', 'Mladi pioniri'), ('SP', 'Stariji pioniri'), ('JUN', 'Juniori'), ('SEN', 'Seniori'), ('VET', 'Veterani')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('DF', 'Defender'), ('MF', 'Midfielder'), ('FW', 'Forward')], max_length=2)),
                ('category', models.CharField(blank=True, choices=[('U9', 'U9'), ('U11', 'U11'), ('MP', 'Mladi pioniri'), ('SP', 'Stariji pioniri'), ('JUN', 'Juniori'), ('SEN', 'Seniori'), ('VET', 'Veterani')], max_length=3, null=True)),
                ('goals', models.PositiveIntegerField(default=0)),
                ('assists', models.PositiveIntegerField(default=0)),
                ('yellow_cards', models.PositiveIntegerField(default=0)),
                ('red_cards', models.PositiveIntegerField(default=0)),
                ('appearances', models.PositiveIntegerField(default=0)),
                ('is_active_member', models.BooleanField(default=True, verbose_name='Aktivan član')),
                ('member_since', models.DateField(default=datetime.date.today, verbose_name='Član od')),
                ('member_until', models.DateField(blank=True, null=True, verbose_name='Član do')),
            ],
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('U', 'Uprava'), ('T', 'Trener'), ('F', 'Fizioterapeut'), ('P', 'Predsjednik'), ('S', 'Sportski direktor'), ('O', 'Ostalo')], max_length=1)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ACTIVATED', 'Aktiviran'), ('DEACTIVATED', 'Deaktiviran'), ('REACTIVATED', 'Ponovno aktiviran'), ('EXTENDED', 'Produženo članstvo')], max_length=20)),
                ('date_from', models.DateField()),
                ('date_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_history', to='main.player')),
            ],
            options={
                'verbose_name_plural': 'Membership histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.player')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='bench_players',
            field=models.ManyToManyField(blank=True, related_name='bench', to='main.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='captain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captain_matches', to='main.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='goalkeeper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goalkeeper_matches', to='main.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='starting_players',
            field=models.ManyToManyField(related_name='starts', to='main.player'),
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveIntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='main.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals_scored', to='main.player')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('Y', 'Yellow Card'), ('R', 'Red Card')], max_length=1)),
                ('minute', models.PositiveIntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='main.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards_received', to='main.player')),
            ],
        ),
        migrations.CreateModel(
            name='Assist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveIntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assists', to='main.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assists_made', to='main.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerCategoryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('U9', 'U9'), ('U11', 'U11'), ('MP', 'Mladi pioniri'), ('SP', 'Stariji pioniri'), ('JUN', 'Juniori'), ('SEN', 'Seniori'), ('VET', 'Veterani')], max_length=3)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_history', to='main.player')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('notes', models.TextField()),
                ('attendees', models.ManyToManyField(related_name='meetings_attended', to='main.staffmember')),
            ],
        ),
    ]
