# Generated by Django 5.1.6 on 2025-08-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiphistory',
            name='action',
            field=models.CharField(choices=[('ACTIVATED', 'Aktiviran'), ('DEACTIVATED', 'Deaktiviran'), ('REACTIVATED', 'Ponovno aktiviran')], max_length=20),
        ),
    ]
