# Generated by Django 5.1.6 on 2025-08-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_membershiphistory_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('Y', 'Žuti karton'), ('R', 'Crveni karton')], max_length=1),
        ),
        migrations.AlterField(
            model_name='match',
            name='category',
            field=models.CharField(choices=[('U9', 'U9'), ('U11', 'U11'), ('MP', 'Mlađi pioniri'), ('SP', 'Stariji pioniri'), ('JUN', 'Juniori'), ('SEN', 'Seniori'), ('VET', 'Veterani')], max_length=3),
        ),
        migrations.AlterField(
            model_name='player',
            name='category',
            field=models.CharField(blank=True, choices=[('U9', 'U9'), ('U11', 'U11'), ('MP', 'Mlađi pioniri'), ('SP', 'Stariji pioniri'), ('JUN', 'Juniori'), ('SEN', 'Seniori'), ('VET', 'Veterani')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('GK', 'Golman'), ('DF', 'Branič'), ('MF', 'Vezni igrač'), ('FW', 'Napadač')], max_length=2),
        ),
        migrations.AlterField(
            model_name='playercategoryhistory',
            name='category',
            field=models.CharField(choices=[('U9', 'U9'), ('U11', 'U11'), ('MP', 'Mlađi pioniri'), ('SP', 'Stariji pioniri'), ('JUN', 'Juniori'), ('SEN', 'Seniori'), ('VET', 'Veterani')], max_length=3),
        ),
    ]
