# Generated by Django 5.1.6 on 2025-05-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_match_result_match_away_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='category',
            field=models.CharField(choices=[('U9', 'U9'), ('U11', 'U11'), ('MP', 'Mladi pioniri'), ('SP', 'Stariji pioniri'), ('JUN', 'Juniori'), ('SEN', 'Seniori'), ('VET', 'Veterani')], default='SEN', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='category',
            field=models.CharField(blank=True, choices=[('U9', 'U9'), ('U11', 'U11'), ('MP', 'Mladi pioniri'), ('SP', 'Stariji pioniri'), ('JUN', 'Juniori'), ('SEN', 'Seniori'), ('VET', 'Veterani')], max_length=3, null=True),
        ),
    ]
