# Generated by Django 5.1.6 on 2025-05-15 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_match_category_alter_player_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assist',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assists_made', to='main.player'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('Y', 'Yellow Card'), ('R', 'Red Card')], max_length=1),
        ),
        migrations.AlterField(
            model_name='card',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards_received', to='main.player'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals_scored', to='main.player'),
        ),
    ]
