# Generated by Django 5.1.6 on 2025-06-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_assist_player_alter_card_card_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='condition',
            field=models.CharField(default='Ispravno', max_length=50),
        ),
        migrations.AddField(
            model_name='equipment',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='type',
            field=models.CharField(choices=[('BALL', 'Lopta'), ('KIT', 'Dres')], default='BALL', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='attendees',
            field=models.ManyToManyField(related_name='meetings_attended', to='main.staffmember'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='title',
            field=models.CharField(default='Zapisnik sastanka', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffmember',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='role',
            field=models.CharField(choices=[('U', 'Uprava'), ('T', 'Trener'), ('F', 'Fizioterapeut'), ('O', 'Ostalo')], max_length=1),
        ),
    ]
