# Generated by Django 5.1.6 on 2025-07-15 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_equipment_condition_equipment_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='category',
            new_name='current_category',
        ),
        migrations.CreateModel(
            name='PlayerCategoryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('U9', 'U9'), ('U11', 'U11'), ('MP', 'Mladi pioniri'), ('SP', 'Stariji pioniri'), ('JUN', 'Juniori'), ('SEN', 'Seniori'), ('VET', 'Veterani')], max_length=3)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_history', to='main.player')),
            ],
            options={
                'verbose_name_plural': 'Player category histories',
                'ordering': ['-is_current', '-start_date'],
            },
        ),
    ]
