# Generated by Django 5.1.6 on 2025-07-15 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_category_player_current_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='current_category',
            new_name='category',
        ),
    ]
