# Generated by Django 5.1.6 on 2025-07-15 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_current_category_player_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerCategoryHistory',
        ),
    ]
