# Generated by Django 5.1.6 on 2025-07-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_delete_playercategoryhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayedCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('U9', 'U9'), ('U11', 'U11'), ('MP', 'Mladi pioniri'), ('SP', 'Stariji pioniri'), ('JUN', 'Juniori'), ('SEN', 'Seniori'), ('VET', 'Veterani')], max_length=3, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='from_youth_academy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='played_categories',
            field=models.ManyToManyField(blank=True, related_name='players', to='main.playedcategory'),
        ),
    ]
