# Generated by Django 5.1.6 on 2025-07-25 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_playedcategory_player_from_youth_academy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='played_categories',
        ),
        migrations.RemoveField(
            model_name='player',
            name='from_youth_academy',
        ),
        migrations.DeleteModel(
            name='PlayedCategory',
        ),
    ]
