# Generated by Django 5.1.6 on 2025-07-25 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_player_played_categories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerCategoryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('U9', 'U9'), ('U11', 'U11'), ('MP', 'Mladi pioniri'), ('SP', 'Stariji pioniri'), ('JUN', 'Juniori'), ('SEN', 'Seniori'), ('VET', 'Veterani')], max_length=3)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_history', to='main.player')),
            ],
        ),
    ]
