# Generated by Django 5.1.6 on 2025-08-07 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_playercategoryhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_active_member',
            field=models.BooleanField(default=True, verbose_name='Aktivan član'),
        ),
        migrations.AddField(
            model_name='player',
            name='member_since',
            field=models.DateField(default=datetime.date.today, verbose_name='Član od'),
        ),
        migrations.AddField(
            model_name='player',
            name='member_until',
            field=models.DateField(blank=True, null=True, verbose_name='Član do'),
        ),
    ]
