# Generated by Django 5.1.6 on 2025-08-09 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_membershiphistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchevent',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='main.match'),
        ),
    ]
