# Generated by Django 5.1.6 on 2025-08-09 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_matchevent_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchevent',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.match'),
        ),
    ]
