# Generated by Django 5.1.6 on 2025-08-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_matchevent_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='home_or_away',
            field=models.CharField(choices=[('H', 'Suhača'), ('A', 'Gostovanje')], max_length=1),
        ),
    ]
