# Generated by Django 5.1.6 on 2025-08-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_match_home_or_away'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmember',
            name='position',
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='role',
            field=models.CharField(choices=[('U', 'Uprava'), ('T', 'Trener'), ('F', 'Fizioterapeut'), ('P', 'Predsjednik'), ('S', 'Sportski direktor'), ('O', 'Ostalo')], max_length=1),
        ),
    ]
